import Head from "next/head";
import Link from "next/link";

const FirstPost = () => {
  return (
    <div>
      <Head>
        <title>Next.js Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>最初の投稿</h1>
      <Link href="/">ホームへ戻る</Link>
    </div>
  )
}

export default FirstPost;